package dev.nicolas.githubsearch.buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

/**
 * Generates `AppConfig` into a source directory wired onto `commonMain`.
 *
 * The generated object is the single place build-time configuration crosses into shared code. That
 * is what lets `:core:network` take the token as a constructor parameter rather than reading a
 * build property itself, keeping the network module free of any knowledge of Gradle.
 *
 * Caching is disabled deliberately: the output can embed an optional GitHub token, and a task whose
 * output contains a secret must never be pushed to a shared build cache.
 */
@DisableCachingByDefault(
    because = "Output can embed an optional token; it must never reach a shared build cache",
)
public abstract class GenerateAppConfigTask : DefaultTask() {
    @get:Input
    public abstract val packageName: Property<String>

    @get:Input
    public abstract val flavor: Property<String>

    @get:Input
    public abstract val baseUrl: Property<String>

    /** Ktor logging level name. Anything shipped must be NONE — see the security gate in CLAUDE.md. */
    @get:Input
    public abstract val logLevel: Property<String>

    /** Optional. Empty means the app runs unauthenticated, which must always work. */
    @get:Input
    public abstract val githubToken: Property<String>

    @get:OutputDirectory
    public abstract val outputDirectory: DirectoryProperty

    @TaskAction
    public fun generate() {
        val pkg = packageName.get()
        val token = githubToken.get()
        val packageDir = outputDirectory.get().asFile.resolve(pkg.replace('.', '/'))
        packageDir.mkdirs()

        // Presence, never the value, and never its length — either would put a secret in CI output.
        logger.lifecycle(
            "AppConfig: flavor=${flavor.get()}, token=${if (token.isEmpty()) "absent" else "present"}",
        )

        packageDir.resolve("AppConfig.kt").writeText(render(pkg, token))
    }

    private fun render(
        pkg: String,
        token: String,
    ): String =
        buildString {
            appendLine("// Generated by GenerateAppConfigTask. Do not edit, do not commit.")
            appendLine("package $pkg")
            appendLine()
            appendLine("/** Build-time configuration: the only crossing point from Gradle into shared code. */")
            appendLine("public object AppConfig {")
            appendLine("    public const val FLAVOR: String = ${token(flavor.get())}")
            appendLine("    public const val BASE_URL: String = ${token(baseUrl.get())}")
            appendLine("    public const val LOG_LEVEL: String = ${token(logLevel.get())}")
            appendLine()
            appendLine("    /** Optional PAT. Empty means unauthenticated, which is a supported mode. */")
            appendLine("    public const val GITHUB_TOKEN: String = ${token(token)}")
            appendLine()
            appendLine("    public val hasToken: Boolean get() = GITHUB_TOKEN.isNotEmpty()")
            appendLine("}")
        }

    /**
     * Renders a Kotlin string literal. A token is opaque text, so a stray quote, backslash, newline, tab
     * or `$` must not be able to break out of the literal and change what compiles.
     *
     * Backslash is escaped first; doing it after the others would double-escape what they inserted.
     */
    private fun token(value: String): String {
        val escaped =
            value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("$", "\\$")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t")
        return "\"" + escaped + "\""
    }
}
